# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-15 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixxie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categ',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='locate',
            new_name='name',
        ),
    ]
