# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-15 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixxie', '0002_auto_20191215_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='categ',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='locate',
        ),
    ]
